version: "3.9"

services:
  http-test-server:
    build: .
    image: http-test-server:latest
    ports:
      - "8080:8080"
    environment:
      - HTTP_TEST_CONFIG=/app/config.yaml
      - HTTP_TEST_HOST=0.0.0.0
      - HTTP_TEST_PORT=8080
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/data
