kafka:
  broker: localhost:9092
  client_id: karussell_node
  default_group_id: KafKarussell_General_Consumer
  # sasl_plain_username: ...
  # sasl_plain_password: ...

logging:
  console_log_level: info
  file_log_level: info
  log_file: ./charybdisk.log

producer:
  enabled: true
  scan_interval: 1
  directories:
    - id: BDKFTP_IN
      path: 'D:\ftproot\ftproot1\BDKFTP\IN'
      backup_directory: 'D:\ftproot\ftproot1\BDKFTP\IN\SAVE'
      file_pattern: "*.txt"
      topic: "VIP_IN.BDKFTP"

    - id: Stadler_TEST_IN
      path: 'D:\ftproot\ftproot2\Stadler_Test\IN'
      backup_directory: 'D:\ftproot\ftproot2\Stadler_Test\IN\SAVE'
      file_pattern: "*"
      topic: "CONV_IN.STADLER_TEST.HASLER_TEST"

    - id: Converter_Stadler_Hasler_Output
      path: 'D:\Converters\Stadler_Hasler_Test\OUT'
      backup_directory: 'D:\Converters\Stadler_Hasler_Test\OUT\SAVE'
      file_pattern: "*"
      topic: "VIP_OUT.Hasler_Test"

consumer:
  enabled: true
  start_from_end: false
  topics:
    - topic: "VIP_IN.BDKFTP"
      group_id: "consumer_group_1"
      output_directory: 'D:\Converters\VIP_IN'
    - topic: "CONV_IN.STADLER_TEST.HASLER_TEST"
      group_id: "consumer_group_2"
      output_directory: 'D:\Converters\Stadler_Hasler_Test\IN'
    - topic: "VIP_OUT.Hasler_Test"
      group_id: "consumer_group_3"
      output_directory: 'D:\ftproot\ftproot1\Hasler\TEST\OUT'
